// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Actor struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	BirthYear   int32  `json:"birth_year"`
	Nationality string `json:"nationality"`
}

type Award struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
}

type Movie struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	ReleaseYear int32  `json:"release_year"`
	Director    string `json:"director"`
	Genre       string `json:"genre"`
}

type NominatedPerformance struct {
	NominationID  int32 `json:"nomination_id"`
	PerformanceID int32 `json:"performance_id"`
}

type Nomination struct {
	ID       int64 `json:"id"`
	MovieID  int32 `json:"movie_id"`
	AwardID  int32 `json:"award_id"`
	Year     int32 `json:"year"`
	IsWinner bool  `json:"is_winner"`
}

type Performance struct {
	ID      int64 `json:"id"`
	ActorID int32 `json:"actor_id"`
	MovieID int32 `json:"movie_id"`
	Year    int32 `json:"year"`
}
